/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRunsRouteImport } from './routes/_dashboard/runs'
import { Route as DashboardKeysRouteImport } from './routes/_dashboard/keys'
import { Route as DashboardRunRunIdRouteImport } from './routes/_dashboard/run.$runId'
import { Route as DashboardRunRunIdIndexRouteImport } from './routes/_dashboard/run.$runId.index'
import { Route as DashboardRunRunIdObservabilityRouteImport } from './routes/_dashboard/run.$runId.observability'
import { Route as DashboardRunRunIdArtifactsRouteImport } from './routes/_dashboard/run.$runId.artifacts'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRunsRoute = DashboardRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRunRunIdRoute = DashboardRunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRunRunIdIndexRoute = DashboardRunRunIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRunRunIdRoute,
} as any)
const DashboardRunRunIdObservabilityRoute =
  DashboardRunRunIdObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => DashboardRunRunIdRoute,
  } as any)
const DashboardRunRunIdArtifactsRoute =
  DashboardRunRunIdArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => DashboardRunRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keys': typeof DashboardKeysRoute
  '/runs': typeof DashboardRunsRoute
  '/run/$runId': typeof DashboardRunRunIdRouteWithChildren
  '/run/$runId/artifacts': typeof DashboardRunRunIdArtifactsRoute
  '/run/$runId/observability': typeof DashboardRunRunIdObservabilityRoute
  '/run/$runId/': typeof DashboardRunRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keys': typeof DashboardKeysRoute
  '/runs': typeof DashboardRunsRoute
  '/run/$runId/artifacts': typeof DashboardRunRunIdArtifactsRoute
  '/run/$runId/observability': typeof DashboardRunRunIdObservabilityRoute
  '/run/$runId': typeof DashboardRunRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/keys': typeof DashboardKeysRoute
  '/_dashboard/runs': typeof DashboardRunsRoute
  '/_dashboard/run/$runId': typeof DashboardRunRunIdRouteWithChildren
  '/_dashboard/run/$runId/artifacts': typeof DashboardRunRunIdArtifactsRoute
  '/_dashboard/run/$runId/observability': typeof DashboardRunRunIdObservabilityRoute
  '/_dashboard/run/$runId/': typeof DashboardRunRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/keys'
    | '/runs'
    | '/run/$runId'
    | '/run/$runId/artifacts'
    | '/run/$runId/observability'
    | '/run/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keys'
    | '/runs'
    | '/run/$runId/artifacts'
    | '/run/$runId/observability'
    | '/run/$runId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/keys'
    | '/_dashboard/runs'
    | '/_dashboard/run/$runId'
    | '/_dashboard/run/$runId/artifacts'
    | '/_dashboard/run/$runId/observability'
    | '/_dashboard/run/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/runs': {
      id: '/_dashboard/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof DashboardRunsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/keys': {
      id: '/_dashboard/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/run/$runId': {
      id: '/_dashboard/run/$runId'
      path: '/run/$runId'
      fullPath: '/run/$runId'
      preLoaderRoute: typeof DashboardRunRunIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/run/$runId/': {
      id: '/_dashboard/run/$runId/'
      path: '/'
      fullPath: '/run/$runId/'
      preLoaderRoute: typeof DashboardRunRunIdIndexRouteImport
      parentRoute: typeof DashboardRunRunIdRoute
    }
    '/_dashboard/run/$runId/observability': {
      id: '/_dashboard/run/$runId/observability'
      path: '/observability'
      fullPath: '/run/$runId/observability'
      preLoaderRoute: typeof DashboardRunRunIdObservabilityRouteImport
      parentRoute: typeof DashboardRunRunIdRoute
    }
    '/_dashboard/run/$runId/artifacts': {
      id: '/_dashboard/run/$runId/artifacts'
      path: '/artifacts'
      fullPath: '/run/$runId/artifacts'
      preLoaderRoute: typeof DashboardRunRunIdArtifactsRouteImport
      parentRoute: typeof DashboardRunRunIdRoute
    }
  }
}

interface DashboardRunRunIdRouteChildren {
  DashboardRunRunIdArtifactsRoute: typeof DashboardRunRunIdArtifactsRoute
  DashboardRunRunIdObservabilityRoute: typeof DashboardRunRunIdObservabilityRoute
  DashboardRunRunIdIndexRoute: typeof DashboardRunRunIdIndexRoute
}

const DashboardRunRunIdRouteChildren: DashboardRunRunIdRouteChildren = {
  DashboardRunRunIdArtifactsRoute: DashboardRunRunIdArtifactsRoute,
  DashboardRunRunIdObservabilityRoute: DashboardRunRunIdObservabilityRoute,
  DashboardRunRunIdIndexRoute: DashboardRunRunIdIndexRoute,
}

const DashboardRunRunIdRouteWithChildren =
  DashboardRunRunIdRoute._addFileChildren(DashboardRunRunIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardRunsRoute: typeof DashboardRunsRoute
  DashboardRunRunIdRoute: typeof DashboardRunRunIdRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardRunsRoute: DashboardRunsRoute,
  DashboardRunRunIdRoute: DashboardRunRunIdRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
