import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { docsNavigationSource, docsPagesSource } from "../src/source";
import type {
  DocsBlock,
  DocsNavigationGroup,
  DocsPage,
  DocsSearchEntry,
  DocsSection,
} from "../src/types";

const OUTPUT_PATH = resolve(import.meta.dir, "../src/generated.ts");

const docsSearchIndex = docsPagesSource.flatMap((page) => [
  pageSearchEntry(page),
  ...page.sections.map((section) => sectionSearchEntry(page, section)),
]);

await mkdir(dirname(OUTPUT_PATH), { recursive: true });
await writeFile(
  OUTPUT_PATH,
  [
    'import type { DocsNavigationGroup, DocsPage, DocsSearchEntry } from "./types";',
    "",
    "// Generated by packages/docs/scripts/generate.ts. Do not edit.",
    `export const docsNavigation = ${toSource(docsNavigationSource)} as const satisfies DocsNavigationGroup[];`,
    "",
    `export const docsPages = ${toSource(docsPagesSource)} as const satisfies DocsPage[];`,
    "",
    `export const docsSearchIndex = ${toSource(docsSearchIndex)} as const satisfies DocsSearchEntry[];`,
    "",
  ].join("\n"),
);

function pageSearchEntry(page: DocsPage): DocsSearchEntry {
  return {
    pageDescription: page.description,
    pageTitle: page.title,
    slug: page.slug,
    text: [page.title, page.description, ...page.sections.map(sectionText)]
      .join(" ")
      .replaceAll(/\s+/g, " ")
      .trim(),
    title: page.title,
  };
}

function sectionSearchEntry(
  page: DocsPage,
  section: DocsSection,
): DocsSearchEntry {
  return {
    anchor: section.id,
    pageDescription: page.description,
    pageTitle: page.title,
    slug: page.slug,
    text: [section.title, sectionText(section)]
      .join(" ")
      .replaceAll(/\s+/g, " ")
      .trim(),
    title: section.title,
  };
}

function sectionText(section: DocsSection) {
  return [section.title, ...section.blocks.map(blockText)].join(" ");
}

function blockText(block: DocsBlock): string {
  switch (block.type) {
    case "code":
      return [block.title, block.language, block.code]
        .filter(isString)
        .join(" ");
    case "codeGroup":
      return block.tabs
        .map((tab) => [tab.title, tab.language, tab.code].join(" "))
        .join(" ");
    case "endpoint":
      return [
        block.method,
        block.path,
        block.title,
        block.body,
        block.request,
        block.response,
      ]
        .filter(isString)
        .join(" ");
    case "list":
      return block.items.join(" ");
    case "note":
      return `${block.title} ${block.text}`;
    case "paragraph":
      return block.text;
    case "steps":
      return block.items.map((item) => `${item.title} ${item.body}`).join(" ");
    case "table":
      return [...block.columns, ...block.rows.flat()].join(" ");
  }
}

function isString(value: string | undefined): value is string {
  return value !== undefined;
}

function toSource(
  value: DocsNavigationGroup[] | DocsPage[] | DocsSearchEntry[],
) {
  return JSON.stringify(value, null, 2);
}
